In [1]:
!pip install pandas numpy matplotlib seaborn scipy sqlalchemy pymysql openpyxl

Requirement already satisfied: pandas in c:\users\91801\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\91801\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: matplotlib in c:\users\91801\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\users\91801\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: scipy in c:\users\91801\anaconda3\lib\site-packages (1.15.3)
Requirement already satisfied: sqlalchemy in c:\users\91801\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pymysql in c:\users\91801\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: openpyxl in c:\users\91801\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91801\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91801\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\91801\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\91801\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\91801\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\91801\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: et-xmlfile in c:\users\91801\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\91801\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime, timedelta

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 2.2.3
NumPy version: 2.1.3

In [4]:
# Number of users
NUM_USERS = 100000

# For reproducibility
np.random.seed(42)

# Create User IDs
users = pd.DataFrame({
    "user_id": [
        f"U{str(i).zfill(6)}"
        for i in range(1, NUM_USERS + 1)
    ]
})

# Assign device
users["device"] = np.random.choice(
    ["Mobile", "Desktop", "Tablet"],
    size=NUM_USERS,
    p=[0.60, 0.35, 0.05]
)

# Assign location
users["location"] = np.random.choice(
    [
        "Mumbai",
        "Pune",
        "Delhi",
        "Bangalore",
        "Hyderabad",
        "Chennai",
        "Kolkata",
        "Ahmedabad"
    ],
    size=NUM_USERS
)

# Assign traffic source
users["traffic_source"] = np.random.choice(
    [
        "Google",
        "Instagram",
        "Facebook",
        "YouTube",
        "Email",
        "Direct",
        "Referral",
        "Paid Ads"
    ],
    size=NUM_USERS,
    p=[0.20, 0.18, 0.12, 0.08, 0.10, 0.12, 0.08, 0.12]
)

# Assign customer type
users["customer_type"] = np.random.choice(
    ["New", "Returning"],
    size=NUM_USERS,
    p=[0.75, 0.25]
)

print("Users generated:", len(users))

Users generated: 100000

In [5]:
users.head(10)

   user_id   device   location traffic_source customer_type
0  U000001   Mobile       Pune         Google     Returning
1  U000002   Tablet  Ahmedabad          Email           New
2  U000003  Desktop    Chennai         Direct           New
3  U000004   Mobile    Kolkata         Direct           New
4  U000005   Mobile     Mumbai       Referral           New
5  U000006   Mobile     Mumbai       Paid Ads           New
6  U000007   Mobile    Chennai       Paid Ads           New
7  U000008  Desktop    Chennai       Facebook           New
8  U000009  Desktop    Kolkata        YouTube           New
9  U000010  Desktop    Chennai       Facebook           New

In [6]:
users.shape

(100000, 5)

In [7]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user_id         100000 non-null  object
 1   device          100000 non-null  object
 2   location        100000 non-null  object
 3   traffic_source  100000 non-null  object
 4   customer_type   100000 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [8]:
users["device"].value_counts()

device
Mobile     59995
Desktop    35134
Tablet      4871
Name: count, dtype: int64

In [9]:
users["traffic_source"].value_counts()

traffic_source
Google       19935
Instagram    18053
Paid Ads     12194
Facebook     12002
Direct       11948
Email        10108
YouTube       7912
Referral      7848
Name: count, dtype: int64

In [10]:
users["customer_type"].value_counts()

customer_type
New          75040
Returning    24960
Name: count, dtype: int64

In [11]:
users["user_id"].duplicated().sum()

np.int64(0)

In [12]:
users.isnull().sum()

user_id           0
device            0
location          0
traffic_source    0
customer_type     0
dtype: int64

In [13]:
# Generate number of sessions for each user
session_counts = np.random.choice(
    [1, 2, 3, 4],
    size=NUM_USERS,
    p=[0.55, 0.25, 0.15, 0.05]
)

print("Total users:", NUM_USERS)
print("Average sessions per user:", session_counts.mean())
print("Maximum sessions for one user:", session_counts.max())

Total users: 100000
Average sessions per user: 1.69834
Maximum sessions for one user: 4

In [14]:
sessions = []

session_id = 1

START_DATE = "2025-01-01"
END_DATE = "2025-06-30"

start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE)

for user, count in zip(users.itertuples(index=False), session_counts):

    for _ in range(count):

        # Random date between start and end date
        session_date = start_date + pd.Timedelta(
            days=np.random.randint(
                0,
                (end_date - start_date).days + 1
            )
        )

        sessions.append({
            "session_id": f"S{session_id:07d}",
            "user_id": user.user_id,
            "session_date": session_date,
            "device": user.device,
            "location": user.location,
            "traffic_source": user.traffic_source,
            "customer_type": user.customer_type
        })

        session_id += 1

# Convert list to DataFrame
sessions = pd.DataFrame(sessions)

print("Total sessions:", len(sessions))

Total sessions: 169834

In [15]:
sessions.head(10)

,session_id,user_id,session_date,device,location,traffic_source,customer_type
0,S0000001,U000001,2025-05-24,Mobile,Pune,Google,Returning
1,S0000002,U000002,2025-01-19,Tablet,Ahmedabad,Email,New
2,S0000003,U000003,2025-02-16,Desktop,Chennai,Direct,New
3,S0000004,U000004,2025-02-18,Mobile,Kolkata,Direct,New
4,S0000005,U000004,2025-03-30,Mobile,Kolkata,Direct,New
5,S0000006,U000005,2025-02-26,Mobile,Mumbai,Referral,New
6,S0000007,U000006,2025-02-25,Mobile,Mumbai,Paid Ads,New
7,S0000008,U000007,2025-03-05,Mobile,Chennai,Paid Ads,New
8,S0000009,U000008,2025-02-11,Desktop,Chennai,Facebook,New
9,S0000010,U000009,2025-04-18,Desktop,Kolkata,YouTube,New

In [16]:
sessions.shape

(169834, 7)

In [17]:
sessions["user_id"].nunique()

100000

In [18]:
sessions["session_id"].nunique()

169834

In [19]:
len(sessions)

169834

In [20]:
print(
    "Rows:",
    len(sessions)
)

print(
    "Unique sessions:",
    sessions["session_id"].nunique()
)

Rows: 169834
Unique sessions: 169834

In [21]:
sessions["session_id"].duplicated().sum()

np.int64(0)

In [22]:
sessions_per_user = (
    sessions
    .groupby("user_id")
    .size()
    .value_counts()
    .sort_index()
)

sessions_per_user

1    55076
2    24964
3    15010
4     4950
Name: count, dtype: int64

In [23]:
print("Minimum date:", sessions["session_date"].min())
print("Maximum date:", sessions["session_date"].max())

Minimum date: 2025-01-01 00:00:00
Maximum date: 2025-06-30 00:00:00

In [24]:
sessions.isnull().sum()

session_id        0
user_id           0
session_date      0
device            0
location          0
traffic_source    0
customer_type     0
dtype: int64

In [25]:
sessions["session_date"] = pd.to_datetime(
    sessions["session_date"]
)

In [26]:
sessions["date"] = sessions["session_date"].dt.date

sessions["year"] = sessions["session_date"].dt.year

sessions["month"] = sessions["session_date"].dt.month

sessions["month_name"] = sessions["session_date"].dt.month_name()

sessions["day_of_week"] = sessions["session_date"].dt.day_name()

sessions["is_weekend"] = (
    sessions["session_date"].dt.dayofweek >= 5
).astype(int)

In [27]:
sessions.head()

,session_id,user_id,session_date,device,location,traffic_source,customer_type,date,year,month,month_name,day_of_week,is_weekend
0,S0000001,U000001,2025-05-24,Mobile,Pune,Google,Returning,2025-05-24,2025,5,May,Saturday,1
1,S0000002,U000002,2025-01-19,Tablet,Ahmedabad,Email,New,2025-01-19,2025,1,January,Sunday,1
2,S0000003,U000003,2025-02-16,Desktop,Chennai,Direct,New,2025-02-16,2025,2,February,Sunday,1
3,S0000004,U000004,2025-02-18,Mobile,Kolkata,Direct,New,2025-02-18,2025,2,February,Tuesday,0
4,S0000005,U000004,2025-03-30,Mobile,Kolkata,Direct,New,2025-03-30,2025,3,March,Sunday,1

In [28]:
# Product categories and products

products = {
    "Electronics": [
        "Laptop",
        "Smartphone",
        "Headphones",
        "Tablet"
    ],

    "Fashion": [
        "Shoes",
        "T-Shirt",
        "Jeans",
        "Jacket"
    ],

    "Home": [
        "Chair",
        "Table",
        "Lamp",
        "Bed"
    ],

    "Beauty": [
        "Perfume",
        "Skincare",
        "Makeup",
        "Haircare"
    ],

    "Sports": [
        "Running Shoes",
        "Cricket Bat",
        "Football",
        "Gym Equipment"
    ]
}

categories = list(products.keys())

print("Categories:", categories)

Categories: ['Electronics', 'Fashion', 'Home', 'Beauty', 'Sports']

In [29]:
price_ranges = {

    "Electronics": (5000, 100000),

    "Fashion": (500, 10000),

    "Home": (1000, 30000),

    "Beauty": (300, 8000),

    "Sports": (500, 20000)
}

price_ranges

{'Electronics': (5000, 100000),
 'Fashion': (500, 10000),
 'Home': (1000, 30000),
 'Beauty': (300, 8000),
 'Sports': (500, 20000)}

In [30]:
# Device conversion multiplier

device_multiplier = {
    "Mobile": 0.82,
    "Desktop": 1.00,
    "Tablet": 0.75
}


# Traffic source conversion multiplier

source_multiplier = {
    "Google": 1.05,
    "Instagram": 0.75,
    "Facebook": 0.70,
    "YouTube": 0.80,
    "Email": 1.20,
    "Direct": 1.05,
    "Referral": 0.95,
    "Paid Ads": 0.85
}


# Customer type multiplier

customer_multiplier = {
    "New": 0.85,
    "Returning": 1.20
}

In [31]:
events = []

event_id = 1

for row in sessions.itertuples(index=False):

    # Random time during the session day
    base_time = row.session_date + pd.Timedelta(
        minutes=np.random.randint(0, 1440)
    )

    # --------------------------------
    # STAGE 1: VISIT
    # --------------------------------

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": base_time,
        "event_type": "visit",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": None,
        "product": None,
        "amount": 0
    })

    event_id += 1

    # --------------------------------
    # Apply segment behavior
    # --------------------------------

    device_factor = device_multiplier[row.device]

    source_factor = source_multiplier[row.traffic_source]

    customer_factor = customer_multiplier[row.customer_type]

    # --------------------------------
    # STAGE 2: PRODUCT VIEW
    # --------------------------------

    product_view_probability = (
        0.75
        * device_factor
        * source_factor
        * customer_factor
    )

    if np.random.random() > product_view_probability:
        continue

    category = np.random.choice(categories)

    product = np.random.choice(
        products[category]
    )

    time2 = base_time + pd.Timedelta(
        minutes=np.random.randint(1, 10)
    )

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": time2,
        "event_type": "product_view",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": category,
        "product": product,
        "amount": 0
    })

    event_id += 1

    # --------------------------------
    # STAGE 3: ADD TO CART
    # --------------------------------

    cart_probability = (
        0.50
        * device_factor
        * source_factor
        * customer_factor
    )

    if np.random.random() > cart_probability:
        continue

    time3 = time2 + pd.Timedelta(
        minutes=np.random.randint(1, 8)
    )

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": time3,
        "event_type": "add_to_cart",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": category,
        "product": product,
        "amount": 0
    })

    event_id += 1

    # --------------------------------
    # STAGE 4: SIGNUP
    # --------------------------------

    signup_probability = (
        0.72
        * device_factor
        * customer_factor
    )

    if np.random.random() > signup_probability:
        continue

    time4 = time3 + pd.Timedelta(
        minutes=np.random.randint(1, 8)
    )

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": time4,
        "event_type": "signup",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": category,
        "product": product,
        "amount": 0
    })

    event_id += 1

    # --------------------------------
    # STAGE 5: CHECKOUT
    # --------------------------------

    checkout_probability = (
        0.80
        * device_factor
        * source_factor
        * customer_factor
    )

    if np.random.random() > checkout_probability:
        continue

    time5 = time4 + pd.Timedelta(
        minutes=np.random.randint(1, 8)
    )

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": time5,
        "event_type": "checkout",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": category,
        "product": product,
        "amount": 0
    })

    event_id += 1

    # --------------------------------
    # STAGE 6: PURCHASE
    # --------------------------------

    purchase_probability = (
        0.65
        * device_factor
        * source_factor
        * customer_factor
    )

    if np.random.random() > purchase_probability:
        continue

    time6 = time5 + pd.Timedelta(
        minutes=np.random.randint(1, 8)
    )

    low, high = price_ranges[category]

    amount = round(
        np.random.uniform(
            low,
            high
        ),
        2
    )

    events.append({
        "event_id": f"E{event_id:08d}",
        "user_id": row.user_id,
        "session_id": row.session_id,
        "event_timestamp": time6,
        "event_type": "purchase",
        "device": row.device,
        "location": row.location,
        "traffic_source": row.traffic_source,
        "customer_type": row.customer_type,
        "product_category": category,
        "product": product,
        "amount": amount
    })

    event_id += 1


print("Events generated:", len(events))

Events generated: 357639

In [32]:
events = pd.DataFrame(events)

print("Rows:", len(events))
print("Columns:", len(events.columns))

Rows: 357639
Columns: 12

In [33]:
events.head(10)

,event_id,user_id,session_id,event_timestamp,event_type,device,location,traffic_source,customer_type,product_category,product,amount
0,E00000001,U000001,S0000001,2025-05-24 06:13:00,visit,Mobile,Pune,Google,Returning,None,None,0.0
1,E00000002,U000002,S0000002,2025-01-19 02:55:00,visit,Tablet,Ahmedabad,Email,New,None,None,0.0
2,E00000003,U000002,S0000002,2025-01-19 03:02:00,product_view,Tablet,Ahmedabad,Email,New,Sports,Gym Equipment,0.0
3,E00000004,U000003,S0000003,2025-02-16 08:32:00,visit,Desktop,Chennai,Direct,New,None,None,0.0
4,E00000005,U000003,S0000003,2025-02-16 08:34:00,product_view,Desktop,Chennai,Direct,New,Electronics,Smartphone,0.0
5,E00000006,U000003,S0000003,2025-02-16 08:39:00,add_to_cart,Desktop,Chennai,Direct,New,Electronics,Smartphone,0.0
6,E00000007,U000004,S0000004,2025-02-18 13:20:00,visit,Mobile,Kolkata,Direct,New,None,None,0.0
7,E00000008,U000004,S0000004,2025-02-18 13:28:00,product_view,Mobile,Kolkata,Direct,New,Sports,Cricket Bat,0.0
8,E00000009,U000004,S0000005,2025-03-30 00:28:00,visit,Mobile,Kolkata,Direct,New,None,None,0.0
9,E00000010,U000004,S0000005,2025-03-30 00:37:00,product_view,Mobile,Kolkata,Direct,New,Home,Bed,0.0

In [34]:
events["event_type"].value_counts()

event_type
visit           169834
product_view     96055
add_to_cart      38646
signup           24712
checkout         17541
purchase         10851
Name: count, dtype: int64

In [35]:
stage_order = [
    "visit",
    "product_view",
    "add_to_cart",
    "signup",
    "checkout",
    "purchase"
]

for stage in stage_order:
    
    count = events[
        events["event_type"] == stage
    ]["user_id"].nunique()
    
    print(stage, ":", count)

visit : 100000
product_view : 68919
add_to_cart : 32726
signup : 21850
checkout : 15582
purchase : 9742

In [36]:
 events["user_id"].nunique()

100000

In [37]:
events["session_id"].nunique()

169834

In [38]:
sessions["session_id"].nunique()

169834

In [39]:
print(
    "Sessions table:",
    sessions["session_id"].nunique()
)

print(
    "Events table:",
    events["session_id"].nunique()
)

Sessions table: 169834
Events table: 169834

In [40]:
purchase_data = events[
    events["event_type"] == "purchase"
]

print(
    "Total purchases:",
    len(purchase_data)
)

print(
    "Total revenue:",
    purchase_data["amount"].sum()
)

print(
    "Average order value:",
    purchase_data["amount"].mean()
)

Total purchases: 10851
Total revenue: 185601596.48000002
Average order value: 17104.561467145886

In [41]:
purchase_data["amount"].describe()

count    10851.000000
mean     17104.561467
std      21774.507338
min        302.400000
25%       4348.305000
50%       8130.980000
75%      19010.690000
max      99788.330000
Name: amount, dtype: float64

In [42]:
purchase_data[
    purchase_data["amount"] < 0
]

Empty DataFrame
Columns: [event_id, user_id, session_id, event_timestamp, event_type, device, location, traffic_source, customer_type, product_category, product, amount]
Index: []

In [43]:
events.isnull().sum()

event_id                 0
user_id                  0
session_id               0
event_timestamp          0
event_type               0
device                   0
location                 0
traffic_source           0
customer_type            0
product_category    169834
product             169834
amount                   0
dtype: int64

In [44]:
events["event_id"].duplicated().sum()

np.int64(0)

In [45]:
sample_session = events["session_id"].iloc[0]

events[
    events["session_id"] == sample_session
].sort_values("event_timestamp")[
    [
        "session_id",
        "event_timestamp",
        "event_type"
    ]
]

  session_id     event_timestamp event_type
0   S0000001 2025-05-24 06:13:00      visit

In [46]:
events.to_csv(
    "../data/raw/user_events_raw.csv",
    index=False
)

print("Raw dataset saved successfully!")

Raw dataset saved successfully!

In [47]:
import os

file_path = "../data/raw/user_events_raw.csv"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print(
        "File size:",
        round(os.path.getsize(file_path) / (1024 * 1024), 2),
        "MB"
    )

File exists: True
File size: 34.01 MB

In [50]:
print(users.shape)
print(sessions.shape)
print(events.shape)

(100000, 5)
(169834, 13)
(357639, 12)

In [51]:
users.to_csv(
    "../data/processed/users.csv",
    index=False
)

sessions.to_csv(
    "../data/processed/sessions.csv",
    index=False
)

print("users.csv created successfully!")
print("sessions.csv created successfully!")

users.csv created successfully!
sessions.csv created successfully!

In [52]:
users.head()

   user_id   device   location traffic_source customer_type
0  U000001   Mobile       Pune         Google     Returning
1  U000002   Tablet  Ahmedabad          Email           New
2  U000003  Desktop    Chennai         Direct           New
3  U000004   Mobile    Kolkata         Direct           New
4  U000005   Mobile     Mumbai       Referral           New

In [53]:
users.columns.tolist()

['user_id', 'device', 'location', 'traffic_source', 'customer_type']

In [54]:
df.columns.tolist()

NameError: name 'df' is not defined

In [55]:
%whos

Variable                   Type         Data/Info
-------------------------------------------------
END_DATE                   str          2025-06-30
NUM_USERS                  int          100000
START_DATE                 str          2025-01-01
amount                     float        4015.65
base_time                  Timestamp    2025-02-20 23:29:00
cart_probability           float        0.365925
categories                 list         n=5
category                   str_         Beauty
checkout_probability       float        0.58548
count                      int          9742
customer_factor            float        0.85
customer_multiplier        dict         n=2
dataframe_columns          function     <function dataframe_colum<...>ns at 0x000001B83105B060>
dataframe_hash             function     <function dataframe_hash at 0x000001B831058220>
datetime                   type         <class 'datetime.datetime'>
device_factor              float        0.82
device_multiplier          dict         n=3
dtypes_str                 function     <function dtypes_str at 0x000001B83105B560>
end_date                   Timestamp    2025-06-30 00:00:00
event_id                   int          357640
events                     DataFrame             event_id  user_i<...>357639 rows x 12 columns]
file_path                  str          ../data/raw/user_events_raw.csv
get_dataframes             function     <function get_dataframes at 0x000001B831058360>
getpass                    module       <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                    module       <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
high                       int          10000
import_pandas_safely       function     <function import_pandas_s<...>ly at 0x000001B82CCF3EC0>
is_data_frame              function     <function is_data_frame at 0x000001B825D9FEC0>
json                       module       <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
low                        int          500
np                         module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os                         module       <module 'os' (frozen)>
pd                         module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plt                        module       <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
price_ranges               dict         n=5
product                    str_         Makeup
product_view_probability   float        0.5488875
products                   dict         n=5
purchase_data              DataFrame             event_id  user_i<...>[10851 rows x 12 columns]
purchase_probability       float        0.5801250000000001
row                        Pandas       Pandas(session_id='S01698<...>'Thursday', is_weekend=0)
sample_session             str          S0000001
session_counts             ndarray      100000: 100000 elems, type `int64`, 800000 bytes (781.25 kb)
session_date               Timestamp    2025-02-20 00:00:00
session_id                 int          169835
sessions                   DataFrame           session_id  user_i<...>169834 rows x 13 columns]
sessions_per_user          Series       1    55076\n2    24964\n3<...>Name: count, dtype: int64
signup_probability         float        0.50184
sns                        module       <module 'seaborn' from 'C<...>s\\seaborn\\__init__.py'>
source_factor              float        1.05
source_multiplier          dict         n=8
stage                      str          purchase
stage_order                list         n=6
start_date                 Timestamp    2025-01-01 00:00:00
time2                      Timestamp    2025-04-09 06:25:00
time3                      Timestamp    2025-04-09 06:28:00
time4                      Timestamp    2025-04-09 06:29:00
time5                      Timestamp    2025-06-05 07:58:00
time6                      Timestamp    2025-05-28 09:17:00
timedelta                  type         <class 'datetime.timedelta'>
user                       Pandas       Pandas(user_id='U100000',<...>le', customer_type='New')
users                      DataFrame           user_id   device  <...>[100000 rows x 5 columns]

In [56]:
users[["user_id", "traffic_source"]].head(10)

   user_id traffic_source
0  U000001         Google
1  U000002          Email
2  U000003         Direct
3  U000004         Direct
4  U000005       Referral
5  U000006       Paid Ads
6  U000007       Paid Ads
7  U000008       Facebook
8  U000009        YouTube
9  U000010       Facebook

In [57]:
users[[
    "user_id",
    "device",
    "location",
    "traffic_source",
    "customer_type"
]].to_csv(
    "../data/processed/users.csv",
    index=False
)

print("users.csv updated successfully!")

users.csv updated successfully!

In [58]:
users[["user_id", "traffic_source"]].head(10)

   user_id traffic_source
0  U000001         Google
1  U000002          Email
2  U000003         Direct
3  U000004         Direct
4  U000005       Referral
5  U000006       Paid Ads
6  U000007       Paid Ads
7  U000008       Facebook
8  U000009        YouTube
9  U000010       Facebook