In [1]:
import pandas as pd
import numpy as np
import os

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
raw_path = "../data/raw/user_events_raw.csv"

df = pd.read_csv(raw_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 357639
Columns: 12

In [3]:
df.head()

,event_id,user_id,session_id,event_timestamp,event_type,device,location,traffic_source,customer_type,product_category,product,amount
0,E00000001,U000001,S0000001,2025-05-24 06:13:00,visit,Mobile,Pune,Google,Returning,NaN,NaN,0.0
1,E00000002,U000002,S0000002,2025-01-19 02:55:00,visit,Tablet,Ahmedabad,Email,New,NaN,NaN,0.0
2,E00000003,U000002,S0000002,2025-01-19 03:02:00,product_view,Tablet,Ahmedabad,Email,New,Sports,Gym Equipment,0.0
3,E00000004,U000003,S0000003,2025-02-16 08:32:00,visit,Desktop,Chennai,Direct,New,NaN,NaN,0.0
4,E00000005,U000003,S0000003,2025-02-16 08:34:00,product_view,Desktop,Chennai,Direct,New,Electronics,Smartphone,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357639 entries, 0 to 357638
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   event_id          357639 non-null  object
 1   user_id           357639 non-null  object
 2   session_id        357639 non-null  object
 3   event_timestamp   357639 non-null  object
 4   event_type        357639 non-null  object
 5   device            357639 non-null  object
 6   location          357639 non-null  object
 7   traffic_source    357639 non-null  object
 8   customer_type     357639 non-null  object
 9   product_category  187805 non-null  object
 10  product           187805 non-null  object
 11  amount            357639 non-null  float64
dtypes: float64(1), object(11)
memory usage: 32.7+ MB

In [5]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 357639
Number of columns: 12

In [6]:
missing_values = df.isnull().sum()

missing_values

event_id                 0
user_id                  0
session_id               0
event_timestamp          0
event_type               0
device                   0
location                 0
traffic_source           0
customer_type            0
product_category    169834
product             169834
amount                   0
dtype: int64

In [7]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [8]:
duplicate_event_ids = df["event_id"].duplicated().sum()

print(
    "Duplicate event IDs:",
    duplicate_event_ids
)

Duplicate event IDs: 0

In [9]:
print(
    "Unique users:",
    df["user_id"].nunique()
)

Unique users: 100000

In [10]:
print(
    "Unique sessions:",
    df["session_id"].nunique()
)

Unique sessions: 169834

In [11]:
df["event_timestamp"].dtype

dtype('O')

In [12]:
df["event_timestamp"] = pd.to_datetime(
    df["event_timestamp"]
)

In [13]:
df["event_timestamp"].dtype

dtype('<M8[ns]')

In [14]:
df["event_type"].value_counts()

event_type
visit           169834
product_view     96055
add_to_cart      38646
signup           24712
checkout         17541
purchase         10851
Name: count, dtype: int64

In [15]:
valid_events = [
    "visit",
    "product_view",
    "add_to_cart",
    "signup",
    "checkout",
    "purchase"
]

invalid_events = df[
    ~df["event_type"].isin(valid_events)
]

print(
    "Invalid events:",
    len(invalid_events)
)

Invalid events: 0

In [16]:
print("Devices:")
print(df["device"].unique())

print("\nLocations:")
print(df["location"].unique())

print("\nTraffic Sources:")
print(df["traffic_source"].unique())

print("\nCustomer Types:")
print(df["customer_type"].unique())

Devices:
['Mobile' 'Tablet' 'Desktop']

Locations:
['Pune' 'Ahmedabad' 'Chennai' 'Kolkata' 'Mumbai' 'Bangalore' 'Delhi'
 'Hyderabad']

Traffic Sources:
['Google' 'Email' 'Direct' 'Referral' 'Paid Ads' 'Facebook' 'YouTube'
 'Instagram']

Customer Types:
['Returning' 'New']

In [17]:
df["amount"].describe()

count    357639.000000
mean        518.963526
std        4794.939678
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max       99788.330000
Name: amount, dtype: float64

In [18]:
df.groupby("event_type")["amount"].sum()

event_type
add_to_cart     0.000000e+00
checkout        0.000000e+00
product_view    0.000000e+00
purchase        1.856016e+08
signup          0.000000e+00
visit           0.000000e+00
Name: amount, dtype: float64

In [19]:
invalid_purchases = df[
    (df["event_type"] == "purchase") &
    (df["amount"] <= 0)
]

print(
    "Invalid purchase records:",
    len(invalid_purchases)
)

Invalid purchase records: 0

In [20]:
invalid_non_purchase = df[
    (df["event_type"] != "purchase") &
    (df["amount"] != 0)
]

print(
    "Invalid non-purchase amounts:",
    len(invalid_non_purchase)
)

Invalid non-purchase amounts: 0

In [21]:
df["date"] = df["event_timestamp"].dt.date

df["year"] = df["event_timestamp"].dt.year

df["month"] = df["event_timestamp"].dt.month

df["month_name"] = df["event_timestamp"].dt.month_name()

df["week"] = df["event_timestamp"].dt.isocalendar().week

df["day_of_week"] = df["event_timestamp"].dt.day_name()

df["hour"] = df["event_timestamp"].dt.hour

df["is_weekend"] = (
    df["event_timestamp"].dt.dayofweek >= 5
).astype(int)

In [22]:
df[
    [
        "event_timestamp",
        "date",
        "year",
        "month",
        "month_name",
        "week",
        "day_of_week",
        "hour",
        "is_weekend"
    ]
].head()

,event_timestamp,date,year,month,month_name,week,day_of_week,hour,is_weekend
0,2025-05-24 06:13:00,2025-05-24,2025,5,May,21,Saturday,6,1
1,2025-01-19 02:55:00,2025-01-19,2025,1,January,3,Sunday,2,1
2,2025-01-19 03:02:00,2025-01-19,2025,1,January,3,Sunday,3,1
3,2025-02-16 08:32:00,2025-02-16,2025,2,February,7,Sunday,8,1
4,2025-02-16 08:34:00,2025-02-16,2025,2,February,7,Sunday,8,1

In [23]:
df["date"]

0         2025-05-24
1         2025-01-19
2         2025-01-19
3         2025-02-16
4         2025-02-16
             ...
357634    2025-04-09
357635    2025-04-09
357636    2025-04-09
357637    2025-04-09
357638    2025-02-20
Name: date, Length: 357639, dtype: object

In [25]:
df["event_date"] = (
    df["event_timestamp"]
    .dt.normalize()
)

In [26]:
df["event_date"].head()

0   2025-05-24
1   2025-01-19
2   2025-01-19
3   2025-02-16
4   2025-02-16
Name: event_date, dtype: datetime64[ns]

In [27]:
df = df.sort_values(
    by=[
        "session_id",
        "event_timestamp"
    ]
).reset_index(drop=True)

In [28]:
event_order = {
    "visit": 1,
    "product_view": 2,
    "add_to_cart": 3,
    "signup": 4,
    "checkout": 5,
    "purchase": 6
}

df["event_order"] = df["event_type"].map(
    event_order
)

In [29]:
df[
    [
        "session_id",
        "event_type",
        "event_order"
    ]
].head(20)

   session_id    event_type  event_order
0    S0000001         visit            1
1    S0000002         visit            1
2    S0000002  product_view            2
3    S0000003         visit            1
4    S0000003  product_view            2
5    S0000003   add_to_cart            3
6    S0000004         visit            1
7    S0000004  product_view            2
8    S0000005         visit            1
9    S0000005  product_view            2
10   S0000006         visit            1
11   S0000007         visit            1
12   S0000008         visit            1
13   S0000009         visit            1
14   S0000009  product_view            2
15   S0000009   add_to_cart            3
16   S0000009        signup            4
17   S0000009      checkout            5
18   S0000010         visit            1
19   S0000010  product_view            2

In [31]:
sequence_check = (
    df.groupby("session_id")["event_order"]
    .apply(lambda x: x.is_monotonic_increasing)
)

print(
    "Sessions with invalid event sequence:",
    (~sequence_check).sum()
)

Sessions with invalid event sequence: 0

In [33]:
session_duration = (
    df.groupby("session_id")["event_timestamp"]
    .agg(
        session_start="min",
        session_end="max"
    )
)

session_duration["duration_minutes"] = (
    (
        session_duration["session_end"]
        - session_duration["session_start"]
    ).dt.total_seconds()
    / 60
)

session_duration.head()

                 session_start         session_end  duration_minutes
session_id
S0000001   2025-05-24 06:13:00 2025-05-24 06:13:00               0.0
S0000002   2025-01-19 02:55:00 2025-01-19 03:02:00               7.0
S0000003   2025-02-16 08:32:00 2025-02-16 08:39:00               7.0
S0000004   2025-02-18 13:20:00 2025-02-18 13:28:00               8.0
S0000005   2025-03-30 00:28:00 2025-03-30 00:37:00               9.0

In [34]:
df = df.merge(
    session_duration[
        ["duration_minutes"]
    ],
    left_on="session_id",
    right_index=True,
    how="left"
)

In [35]:
df[
    [
        "session_id",
        "event_type",
        "duration_minutes"
    ]
].head(10)

  session_id    event_type  duration_minutes
0   S0000001         visit               0.0
1   S0000002         visit               7.0
2   S0000002  product_view               7.0
3   S0000003         visit               7.0
4   S0000003  product_view               7.0
5   S0000003   add_to_cart               7.0
6   S0000004         visit               8.0
7   S0000004  product_view               8.0
8   S0000005         visit               9.0
9   S0000005  product_view               9.0

In [36]:
purchase_users = set(
    df.loc[
        df["event_type"] == "purchase",
        "user_id"
    ]
)

df["user_purchased"] = (
    df["user_id"]
    .isin(purchase_users)
    .astype(int)
)

In [37]:
df[
    [
        "user_id",
        "event_type",
        "user_purchased"
    ]
].head(20)

    user_id    event_type  user_purchased
0   U000001         visit               0
1   U000002         visit               0
2   U000002  product_view               0
3   U000003         visit               0
4   U000003  product_view               0
5   U000003   add_to_cart               0
6   U000004         visit               0
7   U000004  product_view               0
8   U000004         visit               0
9   U000004  product_view               0
10  U000005         visit               0
11  U000006         visit               0
12  U000007         visit               0
13  U000008         visit               0
14  U000008  product_view               0
15  U000008   add_to_cart               0
16  U000008        signup               0
17  U000008      checkout               0
18  U000009         visit               1
19  U000009  product_view               1

In [38]:
print("========== DATA QUALITY SUMMARY ==========")

print("Rows:", len(df))

print("Columns:", len(df.columns))

print("Unique users:", df["user_id"].nunique())

print("Unique sessions:", df["session_id"].nunique())

print("Unique events:", df["event_id"].nunique())

print(
    "Duplicate rows:",
    df.duplicated().sum()
)

print(
    "Duplicate event IDs:",
    df["event_id"].duplicated().sum()
)

print(
    "Invalid event types:",
    (~df["event_type"].isin(valid_events)).sum()
)

print(
    "Negative amounts:",
    (df["amount"] < 0).sum()
)

print(
    "Invalid purchases:",
    (
        (df["event_type"] == "purchase") &
        (df["amount"] <= 0)
    ).sum()
)

========== DATA QUALITY SUMMARY ==========
Rows: 357639
Columns: 24
Unique users: 100000
Unique sessions: 169834
Unique events: 357639
Duplicate rows: 0
Duplicate event IDs: 0
Invalid event types: 0
Negative amounts: 0
Invalid purchases: 0

In [41]:
processed_path = "../data/processed/user_events_clean.csv"

df.to_csv(
    processed_path,
    index=False
)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [42]:
print(
    "File exists:",
    os.path.exists(processed_path)
)

if os.path.exists(processed_path):
    print(
        "File size:",
        round(
            os.path.getsize(processed_path) / (1024 * 1024),
            2
        ),
        "MB"
    )

File exists: True
File size: 54.16 MB